{{- if .Values.app.search.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.search.secret.name }}
data:
  RETAIL_CATALOG_OPENSEARCH_USERNAME: {{ .Values.app.search.username | b64enc | quote }}
  RETAIL_CATALOG_OPENSEARCH_PASSWORD: {{ .Values.app.search.password | b64enc | quote }}
{{- end }}